# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adddialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addDialog(object):
    def setupUi(self, addDialog):
        addDialog.setObjectName("addDialog")
        addDialog.resize(600, 550)
        self.centralwidget = QtWidgets.QWidget(addDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 15, -1, 15)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.nameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout.addWidget(self.nameEdit)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.catEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.catEdit.setObjectName("catEdit")
        self.verticalLayout.addWidget(self.catEdit)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.descEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.descEdit.setObjectName("descEdit")
        self.verticalLayout.addWidget(self.descEdit)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.supidEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.supidEdit.setObjectName("supidEdit")
        self.gridLayout.addWidget(self.supidEdit, 1, 1, 1, 1)
        self.manidEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.manidEdit.setObjectName("manidEdit")
        self.gridLayout.addWidget(self.manidEdit, 3, 1, 1, 1)
        self.supEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.supEdit.setObjectName("supEdit")
        self.gridLayout.addWidget(self.supEdit, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.amountEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.amountEdit.setObjectName("amountEdit")
        self.gridLayout.addWidget(self.amountEdit, 5, 0, 1, 1)
        self.manEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.manEdit.setObjectName("manEdit")
        self.gridLayout.addWidget(self.manEdit, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.priceEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.priceEdit.setObjectName("priceEdit")
        self.gridLayout.addWidget(self.priceEdit, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.storageEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.storageEdit.setObjectName("storageEdit")
        self.verticalLayout.addWidget(self.storageEdit)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.linkEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.linkEdit.setObjectName("linkEdit")
        self.verticalLayout.addWidget(self.linkEdit)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.dataEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dataEdit.setObjectName("dataEdit")
        self.verticalLayout.addWidget(self.dataEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        addDialog.setCentralWidget(self.centralwidget)

        self.retranslateUi(addDialog)
        QtCore.QMetaObject.connectSlotsByName(addDialog)

    def retranslateUi(self, addDialog):
        _translate = QtCore.QCoreApplication.translate
        addDialog.setWindowTitle(_translate("addDialog", "MainWindow"))
        self.label.setText(_translate("addDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Name</span></p></body></html>"))
        self.label_8.setText(_translate("addDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Category</span></p></body></html>"))
        self.label_9.setText(_translate("addDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Description</span></p></body></html>"))
        self.label_5.setText(_translate("addDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Manufacturer ID</span></p></body></html>"))
        self.label_2.setText(_translate("addDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Supplier</span></p></body></html>"))
        self.label_4.setText(_translate("addDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Manufacturer</span></p></body></html>"))
        self.label_3.setText(_translate("addDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Supplier ID</span></p></body></html>"))
        self.label_6.setText(_translate("addDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Amount</span></p></body></html>"))
        self.label_7.setText(_translate("addDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Price</span></p></body></html>"))
        self.label_10.setText(_translate("addDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Storage</span></p></body></html>"))
        self.label_11.setText(_translate("addDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Link</span></p></body></html>"))
        self.label_12.setText(_translate("addDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Datasheet</span></p></body></html>"))

